stages:

  - name: sampling
    dependencies: [combine]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        data_file: {step: combine, output: data_file}
        input_file: {step: init, output: input_file}
        train_samples: {step: init, output: train_samples}
        output_dir: '{workdir}/ml'
      step: {$ref: 'steps.yml#/sampling'}

  - name: training
    dependencies: [sampling]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        input_file: {step: init, output: input_file}
        train_folder: {step: sampling, output: sampling_file}
        output_dir: '{workdir}/ml'
      scatter:
        method: zip
        parameters: [trainfolder]
      step: {$ref: 'steps.yml#/training'}

  - name: evaluating
    dependencies: [training]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        input_file: {step: init, output: input_file}
        model_file: {step: training, output: trained_file}
        data_file: {step: combine, output: data_file}
        output_dir: '{workdir}/ml'
      scatter:
        method: zip
        parameters: [trained_file]
      step: {$ref: 'steps.yml#/evaluating'}

  - name: plotting
    dependencies: [evaluating]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {step: init, output: input_file}
        output_dir: '{workdir}/ml'
        # The following line is wrong.
        # How to get output ZIPs from a 'interpolated-pub' publisher_type step?
        #
        # result_files: {step: evaluating, output: ??????}
        #
        output_file: 'output.txt'
      step: {$ref: 'steps.yml#/plotting'}